// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWG5ducifLnYOwu5IL7yXgen0JCGvd6Gw',
    appId: '1:207728984029:web:ad8dd3e8e1403b5040c034',
    messagingSenderId: '207728984029',
    projectId: 'pronowin-f7653',
    authDomain: 'pronowin-f7653.firebaseapp.com',
    storageBucket: 'pronowin-f7653.firebasestorage.app',
    measurementId: 'G-0ETX0B6PBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ktF5Q-M-uN9PPThIl4Jxue4TPNoxEAs',
    appId: '1:207728984029:android:f95b2bc6deb4a20140c034',
    messagingSenderId: '207728984029',
    projectId: 'pronowin-f7653',
    storageBucket: 'pronowin-f7653.firebasestorage.app',
  );

  // L'app iOS `com.pronowin.app` du projet Firebase, celle de
  // GoogleService-Info.plist. Ces options désignaient `com.example.mobileNew`,
  // l'app du modèle Flutter d'origine, sans clé APNs.
  //
  // Ce n'était pas la cause des notifications refusées (« Invalid APNs
  // credential ») : le jeton de l'iPhone n'a pas changé avec ce correctif, et
  // les refus ont cessé le 30 septembre 2026 quand une clé APNs valable en
  // production a été déposée dans Firebase. Voir docs/ios_envoi.md.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37NbR6EGiW53vcLvZMwSfMgOiO_Jw3uQ',
    appId: '1:207728984029:ios:3f4f84cefd68720d40c034',
    messagingSenderId: '207728984029',
    projectId: 'pronowin-f7653',
    storageBucket: 'pronowin-f7653.firebasestorage.app',
    iosBundleId: 'com.pronowin.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37NbR6EGiW53vcLvZMwSfMgOiO_Jw3uQ',
    appId: '1:207728984029:ios:93b23723fbfafa5540c034',
    messagingSenderId: '207728984029',
    projectId: 'pronowin-f7653',
    storageBucket: 'pronowin-f7653.firebasestorage.app',
    iosBundleId: 'com.example.mobileNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWG5ducifLnYOwu5IL7yXgen0JCGvd6Gw',
    appId: '1:207728984029:web:29af6141daad702a40c034',
    messagingSenderId: '207728984029',
    projectId: 'pronowin-f7653',
    authDomain: 'pronowin-f7653.firebaseapp.com',
    storageBucket: 'pronowin-f7653.firebasestorage.app',
    measurementId: 'G-60PSS89DHX',
  );
}
