import 'dart:convert';
import 'dart:io';

// Run from mobile_new: dart run tool/generate_translations.dart
void main() {
  final messages =
      (jsonDecode(File('lib/l10n/en.json').readAsStringSync()) as Map)
          .cast<String, String>();
  Set<String> slots(String s) =>
      RegExp(r'\{arg\d+\}').allMatches(s).map((m) => m[0]!).toSet();
  String quote(String s) => jsonEncode(s).replaceAll(r'$', r'\$');
  for (final entry in messages.entries) {
    final source = slots(entry.key), translated = slots(entry.value);
    if (source.length != translated.length || !source.containsAll(translated)) {
      throw FormatException('Translation placeholders differ: ${entry.key}');
    }
  }
  File('lib/l10n/catalog_en.dart').writeAsStringSync(
    '// Generated by tool/generate_translations.dart from lib/l10n/en.json.\n'
    '// Do not edit directly.\nconst englishMessages = <String, String>{\n'
    '${messages.entries.map((e) => '  ${quote(e.key)}: ${quote(e.value)},').join('\n')}\n};\n',
  );
  stdout.writeln('${messages.length} translations generated.');
}
